---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Deploy Nginx config (web)
  template:
    src: default.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Restart nginx

- name: Ensure Nginx is enabled and running
  service:
    name: nginx
    state: started
    enabled: true
